/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-07-28 14:22:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class priceAPI_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>EbayRestService</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel='stylesheet' href='");
      out.print( org.webjars.AssetLocator.getWebJarPath("css/bootstrap.min.css") );
      out.write("'>\n");
      out.write("<link rel='stylesheet' href='");
      out.print( org.webjars.AssetLocator.getWebJarPath("css/bootstrap-theme.min.css") );
      out.write("'>\n");
      out.write("<script type='text/javascript' src='");
      out.print( org.webjars.AssetLocator.getWebJarPath("jquery.min.js") );
      out.write("'></script>\n");
      out.write("<script type='text/javascript' src='");
      out.print( org.webjars.AssetLocator.getWebJarPath("js/bootstrap.min.js") );
      out.write("'></script>\n");
      out.write("  \t\n");
      out.write("<!--webfont-->\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>\n");
      out.write("<!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script> -->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("\n");
      out.write("\t\t $(\"#click\").click(function(){\n");
      out.write("\t\t\tvar temp=''; \n");
      out.write("\t\t\t \n");
      out.write("\t\t\t var ip=$(\"#ip\").val();\n");
      out.write("\t\t\t var port=$(\"#port\").val();\n");
      out.write("\t\t\t var subCategory=$(\"#subCategory\").val();\n");
      out.write("\t\t\t var minPrice=$(\"#minPrice\").val();\n");
      out.write("\t\t\t var maxPrice=$(\"#maxPrice\").val();\t\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t// var url=\"http://\"+ip+\":\"+port+\"/eBayRestService/rest1/ebay/\"+color+\"/\"+brand+\"\";\n");
      out.write("\t\t\t //alert(url)\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\ttype :\"GET\",\n");
      out.write("\t\t\t\t\turl: \"http://\"+ip+\":\"+port+\"/eBayREST/webapi/item?subCategory=\"+subCategory+\"&minPrice=\"+minPrice+\"&maxPrice=\"+maxPrice+\"\" ,\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tdataType:\"json\",\n");
      out.write("\t\t\t\t\tsuccess: function(data)\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t\t\t$(\"#di\").empty();\n");
      out.write("\t\t\t\t\t\ttemp='';\n");
      out.write("\t\t\t\t\t\ttemp='<table class=\"table table-striped table-hover \">'+\n");
      out.write("\t\t\t\t\t\t'<thead><tr>'+\n");
      out.write("\t\t\t\t\t\t'<th>Item ID</th> <th>Name</th> <th>Price</th> <th>Discount</th> <th>Seller</th> <th>Category</th> <th>Subcategory</th>'+\n");
      out.write("\t\t\t\t\t\t'<th>Quantity</th> <th>Weight</th> <th>Warranty</th> <th>Brand</th> <th>Discription</th>'+\n");
      out.write("\t\t\t\t\t\t'<th>Color</th>'+\n");
      out.write("\t\t\t\t\t\t'</tr></thead><tbody>';\n");
      out.write("\t\t\t\t\t\t$.each(data,function(i,list)\n");
      out.write("\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\tconsole.log(list);\n");
      out.write("\t\t\t\t\t\t\ttemp+='<tr ><td>'+list.itemId+'</td> <td>'+list.itemName+'</td> <td>'+list.itemPrice+'</td>'+\n");
      out.write("\t\t\t\t\t\t\t'<td>'+list.itemDiscount+'</td> <td>'+list.sellerId+'</td> <td>'+list.category+'</td> '+\n");
      out.write("\t\t\t\t\t\t\t'<td>'+list.subCategory+'</td> <td>'+list.itemQuantity+'</td> <td>'+list.itemWeight+'</td>'+\n");
      out.write("\t\t\t\t\t\t\t'<td>'+list.itemWarranty+'</td> <td>'+list.itemBrand+'</td> <td>'+list.itemDescription+'</td>'+\n");
      out.write("\t\t\t\t\t\t\t'<td>'+list.itemColor+'</td></tr>';\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t$(\"#di\").show();\n");
      out.write("\t\t\t\t\t\t$(\"#di\").append(temp);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t,  \n");
      out.write("\t\t\t       error: function(e){  \n");
      out.write("\t\t\t         alert('Error121212: '+ e);  \n");
      out.write("\t\t\t       } \t\n");
      out.write("\t\t\t});\n");
      out.write("\t\t    });\n");
      out.write("\t\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write(" <h2>Rest Services Client for Ebay</h2>\n");
      out.write(" </center>\n");
      out.write(" <br>\n");
      out.write(" <center>\n");
      out.write(" <h2>List of items of a subCategory having price in the given price range:</h2>\n");
      out.write(" </center>\n");
      out.write("   <br>   <br><a href=\"/eBayREST\">Home</a>\n");
      out.write(" <form class=\"form-horizontal\" action=\"\">\n");
      out.write("  <fieldset>\n");
      out.write("    <legend></legend>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"input\" class=\"col-lg-2 control-label\">IP</label>\n");
      out.write("      <div class=\"col-lg-4\">\n");
      out.write("        <input class=\"form-control\" id=\"ip\" placeholder=\"Enter IP\" type=\"text\" >\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"input\" class=\"col-lg-2 control-label\">PortNO</label>\n");
      out.write("      <div class=\"col-lg-4\">\n");
      out.write("        <input class=\"form-control\" id=\"port\" placeholder=\"Enter Port No\" type=\"text\" >\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"input\" class=\"col-lg-2 control-label\">SubCategory Id</label>\n");
      out.write("      <div class=\"col-lg-4\">\n");
      out.write("        <input class=\"form-control\" id=\"subCategory\" placeholder=\"Enter SubCategory Id\" type=\"text\" >\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"input\" class=\"col-lg-2 control-label\">Enter Minimum Price</label>\n");
      out.write("      <div class=\"col-lg-4\">\n");
      out.write("        <input class=\"form-control\" id=\"minPrice\" placeholder=\"minimum price\" type=\"text\" >\n");
      out.write("      </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("      <label for=\"input\" class=\"col-lg-2 control-label\">Enter Maximum Price</label>\n");
      out.write("      <div class=\"col-lg-4\">\n");
      out.write("        <input class=\"form-control\" id=\"maxPrice\" placeholder=\"maximum price\" type=\"text\" >\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <div class=\"col-lg-5 col-lg-offset-2\">\n");
      out.write("      \n");
      out.write("        <a id=\"click\" class=\"btn btn-success\">Submit</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    </fieldset>\n");
      out.write("    </form>\n");
      out.write(" \n");
      out.write(" <div id=\"di\">\n");
      out.write("</div>\n");
      out.write("<br><a href=\"/eBayREST\">Home</a>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
